# Generated by Django 3.0.10 on 2020-09-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200920_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_content',
            field=models.CharField(max_length=160),
        ),
    ]
