# Generated by Django 3.0.10 on 2020-09-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200920_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_content',
            field=models.ImageField(blank=True, default='', upload_to='post_images'),
        ),
    ]
