# Generated by Django 3.0.10 on 2020-09-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200922_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_content',
            field=models.ImageField(blank=True, default='post_image_default_this_should_not_appear.png', upload_to='post_images'),
        ),
    ]
