# Generated by Django 3.0.10 on 2020-09-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_image_default.jpeg', upload_to='profile_images'),
        ),
    ]
